targets:
  $default:
    builders:
      meta_model_transformer|to_string:
        enabled: true

builders:
  to_string:
    import: 'package:meta_model_transformer/generator/meta_model_transformer.dart'
    builder_factories: ["toStringBuilder"]
    build_extensions: {r"$lib$": ["generated/meta_transformer_generator.x.dart"]}
    # build_extensions: {".dart": [".x.dart"]}
    auto_apply: dependents
    build_to: source
    # applies_builders: ["source_gen:combinign_builder"]