import 'dart:async';
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:meta_model_transformer/utils/class_guard.dart';
import 'package:meta_model_transformer/utils/ext.dart';
import 'package:source_gen/source_gen.dart';

Builder toStringBuilder(BuilderOptions _) => SingleFileAggregateBuilder();

class SingleFileAggregateBuilder extends Builder {
  // Flag runner
  bool _hasRun = false;

  // Base file name
  // with extension [.x.dart]
  String baseFileName = '';

  // Flag to check base class type
  bool baseClassTypeIsAbstract = false;

  // Counter meta
  int checkMetaCount = 0;

  // Field meta value
  String fieldMetaValue = '';

  // List consumer class [registry]
  List<String> registry = [];

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    if (_hasRun) return;
    if (buildStep.inputId.path.endsWith('x.dart')) return;

    _hasRun = true;

    final StringBuffer buffer = StringBuffer();
    final List<AssetId> assets = await buildStep
        .findAssets(Glob('lib/**.dart'))
        .toList();

    // Header
    buffer.writeln('''
// **************************************************************************
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************
// 
// WARNING: This file has been automatically generated by the code generator.
// Any manual modifications to this file WILL BE REMOVED and OVERWRITTEN
// the next time the 'build_runner' command is executed.
//
// To make changes, please modify the original model/registry class instead.
// **************************************************************************
// ignore_for_file: type=lint
''');

    // Generated import
    final String writePart = await _generateImport(
      assets,
      buildStep: buildStep,
    );
    buffer.write(writePart);

    for (final AssetId file in assets) {
      // Guarding data
      // continue to next loop if data is not valid
      if (await ClassGuard.guardData(file, buildStep)) continue;

      // Setup fist meta model transform
      await _setupBaseMetaTransformer(file, buildStep);

      final (
        bool metaBaseIsEmpty,
        Iterable<AnnotatedElement> dataTransform,
      ) = await ClassGuard.checkFileContainAnnotation(
        'Transform',
        file: file,
        buildStep: buildStep,
      );

      if (metaBaseIsEmpty) continue;
      for (final AnnotatedElement res in dataTransform) {
        if (res.element is! ClassElement) continue;
        final String? className = res.element.name;

        // Check is this class had a fromJson constructor
        if (!ClassGuard.isValidFromJson(res.element as ClassElement)) {
          throw InvalidGenerationSource(
            'Class $className must have a fromJson constructor',
            todo:
                'Add factory fromJson(Map<String, dynamic> json) into $className',
          );
        } else {
          // Append class
          registry.add(className!);
        }
      }
    }

    // Prevent generator when `MetaUse` annotation not found
    ClassGuard.preventSomeConditionUsingMetaUseAnnotation(
      requiredVariableName: fieldMetaValue,
      baseMetaCount: checkMetaCount,
    );

    // Generator
    buffer.write(await _writeGeneratorClass());

    // Write extension
    buffer.write(
      writeExtension(
        baseClass: baseFileName,
        registry: registry,
        fieldName: fieldMetaValue,
      ),
    );

    if (checkMetaCount == 0) {
      return;
    }

    // Write to file
    if (checkMetaCount != 0) {
      final output = AssetId(
        buildStep.inputId.package,
        'lib/generated/meta_transformer_generator.x.dart',
      );
      await buildStep.writeAsString(output, buffer.toString());
    }
    _hasRun = false;
  }

  @override
  Map<String, List<String>> get buildExtensions => {
    r'$lib$': ['generated/meta_transformer_generator.x.dart'],
  };

  /// Setup base meta model transform
  ///
  /// This setup will set once, if generator detect [MetaUse] more than once
  /// this function will throw [InvalidGenerationSource]
  Future<void> _setupBaseMetaTransformer(
    AssetId file,
    BuildStep buildStep,
  ) async {
    final (
      bool metaBaseIsEmpty,
      Iterable<AnnotatedElement> dataMetaBase,
    ) = await ClassGuard.checkFileContainAnnotation(
      'MetaUse',
      file: file,
      buildStep: buildStep,
    );

    for (AnnotatedElement annotation in dataMetaBase) {
      checkMetaCount++;

      final ClassElement classElement = annotation.element as ClassElement;

      // Change name generator
      baseFileName = annotation.element.name ?? '';

      // Set field value
      fieldMetaValue = annotation.annotation.peek('field')?.stringValue ?? '';

      // Check class type
      if (classElement.isAbstract) {
        baseClassTypeIsAbstract = true;
        for (var e in classElement.constructors) {
          if (e.formalParameters.isEmpty) {
            throw InvalidGenerationSource(
              'Constructor must have [$annotation as dynamic]',
              todo:
                  'Add field $fieldMetaValue into constuctor parameter as dynamic',
              element: annotation.element,
            );
          }
        }
      }

      // Precent consumer has a field
      if (!ClassGuard.isClassHasField(fieldMetaValue, data: classElement)) {
        // Throw exception
        throw InvalidGenerationSource(
          'Field $fieldMetaValue not found in ${annotation.element.name}',
          todo:
              'Add field $fieldMetaValue into ${annotation.element.name} as Map<String, dynamic>',
          element: annotation.element,
        );
      }
    }
  }

  Future<String> _generateImport(
    Iterable<AssetId> assets, {
    required BuildStep buildStep,
  }) async {
    final StringBuffer partBuffer = StringBuffer();

    for (final AssetId file in assets) {
      // Just skip if not valid
      if (await ClassGuard.guardData(file, buildStep)) continue;

      final (
        bool metaUseIsEmpty,
        _,
      ) = await ClassGuard.checkFileContainAnnotation(
        'MetaUse',
        file: file,
        buildStep: buildStep,
      );

      final (
        bool transformIsEmpty,
        _,
      ) = await ClassGuard.checkFileContainAnnotation(
        'Transform',
        file: file,
        buildStep: buildStep,
      );

      final String filePath = file.path.substring(4);

      if (!metaUseIsEmpty || !transformIsEmpty) {
        partBuffer.writeln('import \'../$filePath\';');
      }
    }

    return partBuffer.toString();
  }

  Future<StringBuffer> _writeGeneratorClass() async {
    final StringBuffer buffer = StringBuffer();

    buffer.writeln('''

typedef jsonParser = dynamic Function(dynamic);

class _\$MetaModelTransformer {
  static Map<String, jsonParser> registry = {

    // Registry for parsing List<T> objects.
    //
    // Stores parser functions for each registered model that transform
    // a JSON array into a strongly typed List<T>. Parsers are executed
    // lazily, meaning only the parser matching the requested generic
    // type is invoked.
${writeListOutputData(registry, fieldMetaValue)}
    // Registry for parsing single objects [T].
    //
    // Stores parser functions for each registered model that convert
    // a JSON object [Map<String, dynamic>] into its corresponding
    // strongly typed model instance. The parser is selected based on
    // the requested generic type and is executed only when getData()
    // is called.
${writeOutputData(registry, fieldMetaValue)}
  };
}''');

    return buffer;
  }
}
